name: Deploy to Choreo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create the .env file with GitHub Secrets
      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      # # Your deployment steps go here, using the generated .env file
      # - name: Deploy to Choreo
      #   run: |
      #     # Your Choreo deployment command
      #     # e.g., deploy.sh, or any other deployment steps required by Choreo
